Repository ministryofjustice/offender-risk-profiler, pull requests merged in 2022-04, with the labels that each got.

#170 #SED-7 - Update Dependencies
  .circleci/config.yml
  .gitignore
  .trivyignore
  build.gradle.kts
Labels: dependencies

#171 SED-14: added trivvy ignore file for jackson alert
  .trivvyignore
Labels: CVE

#173 Sed 14
  .trivyignore
Labels: CVE

#172 Added badges
  README.md
Labels: documentation

#175 SED-16 - Updated hmpps.gradle-spring-boot to 4.1.4
  build.gradle.kts
Labels: dependencies

#177 ⬆ GSP Update
  build.gradle.kts
Labels: dependencies

#179 [DSE-65] Update build.gradle.kts
  build.gradle.kts
Labels: dependencies

#180 [DSE-47] GHA to update Gradle Spring Boot
  .github/workflows/main.yml
Labels: enhancement

#178 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies
